# Data Manipulation Studio

For this studio, we will revisit our California farmers looking for advice on growing pumpkins and the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [4]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import matplotlib 
import matplotlib.pyplot as plt
import numpy as np


baltimore_df = pd.read_csv('/Users/kay/data-manipulation/dataset/baltimore_9-24-2016_9-30-2017.csv')
boston_df = pd.read_csv('/Users/kay/data-manipulation/dataset/boston_9-24-2016_9-30-2017.csv')
newyork_df = pd.read_csv('/Users/kay/data-manipulation/dataset/new-york_9-24-2016_9-30-2017.csv')
philadelphia_df = pd.read_csv('/Users/kay/data-manipulation/dataset/philadelphia_9-24-2016_9-30-2017.csv')

In [5]:
baltimore_df.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,04/29/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
1,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,05/06/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
2,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,11/05/2016,90,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [6]:
boston_df.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,180,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [7]:
newyork_df.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,120,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [8]:
philadelphia_df.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/16/2017,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

## Clean Your Data

In the last lesson, we cleaned the data to related to San Francisco. Pull up your notebook from the last lesson and use your cleaning skills to clean the dataframes as necessary.

In [10]:
# Clean your data here!
baltimore_df.shape

(153, 25)

In [24]:
baltimore_df.columns

Index(['Commodity Name', 'City Name', 'Type', 'Package', 'Variety',
       'Sub Variety', 'Grade', 'Date', 'Low Price', 'High Price', 'Mostly Low',
       'Mostly High', 'Origin', 'Origin District', 'Item Size', 'Color',
       'Environment', 'Unit of Sale', 'Quality', 'Condition', 'Appearance',
       'Storage', 'Crop', 'Repack', 'Trans Mode'],
      dtype='object')

In [11]:
boston_df.shape

(352, 25)

In [25]:
boston_df.columns

Index(['Commodity Name', 'City Name', 'Type', 'Package', 'Variety',
       'Sub Variety', 'Grade', 'Date', 'Low Price', 'High Price', 'Mostly Low',
       'Mostly High', 'Origin', 'Origin District', 'Item Size', 'Color',
       'Environment', 'Unit of Sale', 'Quality', 'Condition', 'Appearance',
       'Storage', 'Crop', 'Repack', 'Trans Mode'],
      dtype='object')

In [12]:
newyork_df.shape

(112, 25)

In [26]:
newyork_df.columns

Index(['Commodity Name', 'City Name', 'Type', 'Package', 'Variety',
       'Sub Variety', 'Grade', 'Date', 'Low Price', 'High Price', 'Mostly Low',
       'Mostly High', 'Origin', 'Origin District', 'Item Size', 'Color',
       'Environment', 'Unit of Sale', 'Quality', 'Condition', 'Appearance',
       'Storage', 'Crop', 'Repack', 'Trans Mode'],
      dtype='object')

In [13]:
philadelphia_df.shape

(57, 25)

In [27]:
philadelphia_df.columns

Index(['Commodity Name', 'City Name', 'Type', 'Package', 'Variety',
       'Sub Variety', 'Grade', 'Date', 'Low Price', 'High Price', 'Mostly Low',
       'Mostly High', 'Origin', 'Origin District', 'Item Size', 'Color',
       'Environment', 'Unit of Sale', 'Quality', 'Condition', 'Appearance',
       'Storage', 'Crop', 'Repack', 'Trans Mode'],
      dtype='object')

In [20]:
def missingpct(df):
    for col in df.columns:
        pct_missing = np.mean(df[col].isnull())
        print('{} - {}%'.format(col, round(pct_missing*100)))
        
    total_cells = np.product(df.shape)

    missing_cells = pd.isnull(df).sum()

    total_missing = missing_cells.sum()

    percentage_missing = round((total_missing/total_cells), 2) *100

    print(percentage_missing, "% Missing cells from the data")    
    
missingpct(baltimore_df)

Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 1%
Sub Variety - 84%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 3%
Origin District - 100%
Item Size - 16%
Color - 80%
Environment - 100%
Unit of Sale - 84%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
51.0 % Missing cells from the data

In [21]:
missingpct(boston_df)

Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 92%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 81%
Item Size - 1%
Color - 14%
Environment - 100%
Unit of Sale - 87%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
47.0 % Missing cells from the data

In [22]:
missingpct(newyork_df)

Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 84%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 87%
Item Size - 7%
Color - 81%
Environment - 100%
Unit of Sale - 78%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
49.0 % Missing cells from the data

In [23]:
missingpct(philadelphia_df)

Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 79%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 100%
Item Size - 21%
Color - 100%
Environment - 100%
Unit of Sale - 81%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
51.0 % Missing cells from the data

In [ ]:
def advcleaning(df):
    df.dropna(how='all',axis=1)
    for data
        if data.

In [47]:
def cleaning(df):
    df.dropna(axis=1, inplace=True)
    
    
cleaning(baltimore_df)
baltimore_df

,Commodity Name,City Name,Package,Date,Low Price,High Price,Mostly Low,Mostly High,Repack
0,PUMPKINS,BALTIMORE,24 inch bins,04/29/2017,270,280.0,270,280.0,E
1,PUMPKINS,BALTIMORE,24 inch bins,05/06/2017,270,280.0,270,280.0,E
2,PUMPKINS,BALTIMORE,24 inch bins,09/24/2016,160,160.0,160,160.0,N
3,PUMPKINS,BALTIMORE,24 inch bins,09/24/2016,160,160.0,160,160.0,N
4,PUMPKINS,BALTIMORE,24 inch bins,11/05/2016,90,100.0,90,100.0,N
...,...,...,...,...,...,...,...,...,...
148,PUMPKINS,BALTIMORE,1/2 bushel cartons,09/30/2017,18,18.0,18,18.0,N
149,PUMPKINS,BALTIMORE,1/2 bushel cartons,09/30/2017,18,18.0,18,18.0,N
150,PUMPKINS,BALTIMORE,1/2 bushel cartons,09/24/2016,15,15.0,15,15.0,N
151,PUMPKINS,BALTIMORE,1/2 bushel cartons,10/01/2016,15,15.0,15,15.0,N
152,PUMPKINS,BALTIMORE,1/2 bushel cartons,10/08/2016,15,15.0,15,15.0,N

In [48]:
cleaning(boston_df)
boston_df

,Commodity Name,City Name,Package,Variety,Date,Low Price,High Price,Mostly Low,Mostly High,Origin,Repack
0,PUMPKINS,BOSTON,36 inch bins,HOWDEN TYPE,09/24/2016,160,200,165,165,CANADA,N
1,PUMPKINS,BOSTON,36 inch bins,HOWDEN TYPE,09/24/2016,160,200,165,165,CANADA,N
2,PUMPKINS,BOSTON,36 inch bins,HOWDEN TYPE,09/24/2016,160,200,165,165,CANADA,N
3,PUMPKINS,BOSTON,36 inch bins,HOWDEN TYPE,09/24/2016,160,200,165,165,CANADA,N
4,PUMPKINS,BOSTON,36 inch bins,HOWDEN TYPE,09/24/2016,160,180,165,165,CANADA,N
...,...,...,...,...,...,...,...,...,...,...,...
347,PUMPKINS,BOSTON,1/2 bushel cartons,MINIATURE,10/22/2016,15,18,15,15,MASSACHUSETTS,N
348,PUMPKINS,BOSTON,1/2 bushel cartons,MINIATURE,10/29/2016,15,18,15,15,MASSACHUSETTS,N
349,PUMPKINS,BOSTON,1/2 bushel cartons,MINIATURE,10/29/2016,15,18,15,15,MASSACHUSETTS,N
350,PUMPKINS,BOSTON,1/2 bushel cartons,MINIATURE,11/05/2016,15,18,15,15,MASSACHUSETTS,N
351,PUMPKINS,BOSTON,1/2 bushel cartons,MINIATURE,11/05/2016,15,18,15,15,MASSACHUSETTS,N

In [49]:
cleaning(newyork_df)
newyork_df

,Commodity Name,City Name,Package,Variety,Date,Low Price,High Price,Mostly Low,Mostly High,Origin,Repack
0,PUMPKINS,NEW YORK,36 inch bins,HOWDEN TYPE,09/24/2016,150,170,150,170,MICHIGAN,N
1,PUMPKINS,NEW YORK,36 inch bins,HOWDEN TYPE,09/24/2016,150,170,150,170,MICHIGAN,N
2,PUMPKINS,NEW YORK,36 inch bins,HOWDEN TYPE,09/24/2016,130,150,130,150,NEW JERSEY,N
3,PUMPKINS,NEW YORK,36 inch bins,HOWDEN TYPE,09/24/2016,130,150,130,150,NEW JERSEY,N
4,PUMPKINS,NEW YORK,36 inch bins,HOWDEN TYPE,09/24/2016,120,140,120,140,NEW YORK,N
...,...,...,...,...,...,...,...,...,...,...,...
107,PUMPKINS,NEW YORK,bushel cartons,MINIATURE,09/09/2017,32,32,32,32,OHIO,N
108,PUMPKINS,NEW YORK,1 1/9 bushel crates,MINIATURE,10/08/2016,18,18,18,18,NEW YORK,N
109,PUMPKINS,NEW YORK,1 1/9 bushel crates,MINIATURE,10/08/2016,18,18,18,18,NEW YORK,N
110,PUMPKINS,NEW YORK,1 1/9 bushel crates,MINIATURE,10/15/2016,18,18,18,18,NEW YORK,N
111,PUMPKINS,NEW YORK,1 1/9 bushel crates,MINIATURE,10/15/2016,18,18,18,18,NEW YORK,N

In [58]:
cleaning(philadelphia_df)
philadelphia_df

,Commodity Name,City Name,Package,Variety,Date,Low Price,High Price,Mostly Low,Mostly High,Origin,Repack
0,PUMPKINS,PHILADELPHIA,24 inch bins,HOWDEN TYPE,09/16/2017,140,150,140,150,PENNSYLVANIA,N
1,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/24/2016,150,150,150,150,NEW YORK,N
2,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/24/2016,150,150,150,150,NEW YORK,N
3,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/24/2016,150,160,150,160,PENNSYLVANIA,N
4,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/01/2016,140,140,140,140,NEW JERSEY,N
5,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/01/2016,140,140,140,140,PENNSYLVANIA,N
6,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/01/2016,120,120,120,120,PENNSYLVANIA,N
7,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/08/2016,140,155,140,155,NEW JERSEY,N
8,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/08/2016,120,120,120,120,NEW JERSEY,N
9,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/15/2016,120,125,120,125,PENNSYLVANIA,N
10,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/15/2016,100,125,100,125,PENNSYLVANIA,N
11,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/22/2016,130,140,130,140,NEW JERSEY,N
12,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/22/2016,120,120,120,120,PENNSYLVANIA,N
13,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/22/2016,130,140,130,140,PENNSYLVANIA,N
14,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/22/2016,100,120,100,120,PENNSYLVANIA,N
15,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/29/2016,130,140,130,140,NEW JERSEY,N
16,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/29/2016,120,120,120,120,PENNSYLVANIA,N
17,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/29/2016,130,140,130,140,PENNSYLVANIA,N
18,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,10/29/2016,100,120,120,120,PENNSYLVANIA,N
19,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/16/2017,120,120,120,120,PENNSYLVANIA,N
20,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/16/2017,120,150,120,150,PENNSYLVANIA,N
21,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/23/2017,140,140,140,140,DELAWARE,N
22,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/23/2017,150,150,150,150,DELAWARE,N
23,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/23/2017,120,150,120,150,NEW YORK,N
24,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/23/2017,140,150,140,150,PENNSYLVANIA,N
25,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/23/2017,140,150,140,150,PENNSYLVANIA,N
26,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/30/2017,140,140,140,140,DELAWARE,N
27,PUMPKINS,PHILADELPHIA,36 inch bins,HOWDEN TYPE,09/30/2017,140,140,140,140,DELAWARE,N
28,PUMPKINS,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,10/15/2016,12,14,12,14,OHIO,N
29,PUMPKINS,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,10/22/2016,12,12,12,12,OHIO,N
30,PUMPKINS,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,10/29/2016,12,12,12,12,OHIO,N
31,PUMPKINS,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,08/26/2017,18,20,18,20,MICHIGAN,N
32,PUMPKINS,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,09/16/2017,18,18,18,18,OHIO,N
33,PUMPKINS,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,09/23/2017,18,22,18,22,OHIO,N
34,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,10/01/2016,250,250,250,250,PENNSYLVANIA,N
35,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,10/15/2016,140,140,140,140,PENNSYLVANIA,N
36,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,10/22/2016,140,150,140,150,PENNSYLVANIA,N
37,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,10/22/2016,75,100,75,100,PENNSYLVANIA,N
38,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,10/29/2016,140,150,140,150,PENNSYLVANIA,N
39,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,10/29/2016,75,100,75,100,PENNSYLVANIA,N
40,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,09/23/2017,180,180,180,180,DELAWARE,N
41,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,09/23/2017,140,140,140,140,DELAWARE,N
42,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,09/23/2017,180,180,180,180,NEW YORK,N
43,PUMPKINS,PHILADELPHIA,24 inch bins,PIE TYPE,09/30/2017,140,140,140,140,DELAWARE,N
44,PUMPKINS,PHILADELPHIA,24 inch bins,KNUCKLE HEAD,10/08/2016,210,210,210,210,NEW JERSEY,N
45,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,09/24/2016,17,18,17,18,OHIO,N
46,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,10/01/2016,18,18,18,18,NEW JERSEY,N
47,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,10/01/2016,17,18,17,18,OHIO,N
48,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,10/08/2016,15,15,15,15,OHIO,N
49,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,10/15/2016,15,18,15,18,OHIO,N
50,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,10/22/2016,16,18,16,18,OHIO,N
51,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,10/29/2016,16,18,16,18,OHIO,N
52,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,11/05/2016,16,18,16,18,OHIO,N
53,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,08/26/2017,18,20,18,20,MICHIGAN,N
54,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,09/16/2017,16,16,16,16,OHIO,N
55,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,09/23/2017,15,16,15,16,OHIO,N
56,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,MINIATURE,09/30/2017,15,18,15,18,OHIO,N

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [55]:
# Combine the four dataframes into one!
northeast_dfs = [baltimore_df , boston_df , newyork_df , philadelphia_df]

northeast_df = pd.concat(northeast_dfs)
northeast_df

,Commodity Name,City Name,Package,Date,Low Price,High Price,Mostly Low,Mostly High,Repack,Variety,Origin
0,PUMPKINS,BALTIMORE,24 inch bins,04/29/2017,270,280.0,270,280.0,E,NaN,NaN
1,PUMPKINS,BALTIMORE,24 inch bins,05/06/2017,270,280.0,270,280.0,E,NaN,NaN
2,PUMPKINS,BALTIMORE,24 inch bins,09/24/2016,160,160.0,160,160.0,N,NaN,NaN
3,PUMPKINS,BALTIMORE,24 inch bins,09/24/2016,160,160.0,160,160.0,N,NaN,NaN
4,PUMPKINS,BALTIMORE,24 inch bins,11/05/2016,90,100.0,90,100.0,N,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
52,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,11/05/2016,16,18.0,16,18.0,N,MINIATURE,OHIO
53,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,08/26/2017,18,20.0,18,20.0,N,MINIATURE,MICHIGAN
54,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,09/16/2017,16,16.0,16,16.0,N,MINIATURE,OHIO
55,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,09/23/2017,15,16.0,15,16.0,N,MINIATURE,OHIO
56,PUMPKINS,PHILADELPHIA,1/2 bushel cartons,09/30/2017,15,18.0,15,18.0,N,MINIATURE,OHIO

In [59]:
missingpct(northeast_df)

Commodity Name - 0%
City Name - 0%
Package - 0%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Repack - 0%
Variety - 23%
Origin - 23%
4.0 % Missing cells from the data

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of unit of sale in the Northeast region? In the last lesson, we learned that a unit of sale could be something like a bin or individually. 
2. What is the average number of pumpkins for each variety that came into terminal markets for the year by region? Pumpkin varieties include Howden and Fairytale pumpkins.

In [66]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.
unit_of_sale = northeast_df[['Package']].value_counts()
unit_of_sale

Package
36 inch bins            316
24 inch bins            178
1/2 bushel cartons       97
1 1/9 bushel cartons     48
1 1/9 bushel crates      17
50 lb sacks               9
bushel cartons            7
each                      2
dtype: int64

In [69]:
northeast_df.groupby(['Package']).mean()

                       Low Price  High Price  Mostly Low  Mostly High
Package
1 1/9 bushel cartons   15.875000   16.739583   15.875000    16.489583
1 1/9 bushel crates    16.058824   16.705882   16.058824    16.058824
1/2 bushel cartons     16.030928   17.597938   16.092784    16.639175
24 inch bins          188.005618  202.808989  195.421348   201.994382
36 inch bins          170.458861  196.550633  177.373418   184.905063
50 lb sacks            25.111111   25.333333   25.111111    25.333333
bushel cartons         20.571429   22.857143   21.714286    22.000000
each                   75.000000   80.000000   75.000000    80.000000

In [80]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
northeast_df.groupby(['City Name','Variety']).agg(['min','max'])

                                      Commodity Name            \
                                                 min       max
City Name    Variety
BOSTON       BIG MACK TYPE                  PUMPKINS  PUMPKINS
             BLUE TYPE                      PUMPKINS  PUMPKINS
             CINDERELLA                     PUMPKINS  PUMPKINS
             FAIRYTALE                      PUMPKINS  PUMPKINS
             HOWDEN TYPE                    PUMPKINS  PUMPKINS
             KNUCKLE HEAD                   PUMPKINS  PUMPKINS
             MINIATURE                      PUMPKINS  PUMPKINS
             PIE TYPE                       PUMPKINS  PUMPKINS
NEW YORK     BIG MACK TYPE                  PUMPKINS  PUMPKINS
             HOWDEN TYPE                    PUMPKINS  PUMPKINS
             KNUCKLE HEAD                   PUMPKINS  PUMPKINS
             MINIATURE                      PUMPKINS  PUMPKINS
             MIXED HEIRLOOM VARIETIES       PUMPKINS  PUMPKINS
             PIE TYPE                       PUMPKINS  PUMPKINS
PHILADELPHIA HOWDEN TYPE                    PUMPKINS  PUMPKINS
             KNUCKLE HEAD                   PUMPKINS  PUMPKINS
             MINIATURE                      PUMPKINS  PUMPKINS
             PIE TYPE                       PUMPKINS  PUMPKINS

                                                    Package  \
                                                        min
City Name    Variety
BOSTON       BIG MACK TYPE                     24 inch bins
             BLUE TYPE                         24 inch bins
             CINDERELLA                        24 inch bins
             FAIRYTALE                   1/2 bushel cartons
             HOWDEN TYPE                       36 inch bins
             KNUCKLE HEAD                      24 inch bins
             MINIATURE                   1/2 bushel cartons
             PIE TYPE                  1 1/9 bushel cartons
NEW YORK     BIG MACK TYPE                             each
             HOWDEN TYPE                       36 inch bins
             KNUCKLE HEAD                      36 inch bins
             MINIATURE                  1 1/9 bushel crates
             MIXED HEIRLOOM VARIETIES          24 inch bins
             PIE TYPE                  1 1/9 bushel cartons
PHILADELPHIA HOWDEN TYPE                       24 inch bins
             KNUCKLE HEAD                      24 inch bins
             MINIATURE                   1/2 bushel cartons
             PIE TYPE                  1 1/9 bushel cartons

                                                                 Date  \
                                                      max         min
City Name    Variety
BOSTON       BIG MACK TYPE                   36 inch bins  09/09/2017
             BLUE TYPE                       24 inch bins  09/24/2016
             CINDERELLA                      24 inch bins  09/24/2016
             FAIRYTALE                       24 inch bins  09/24/2016
             HOWDEN TYPE                     36 inch bins  09/23/2017
             KNUCKLE HEAD                    24 inch bins  09/24/2016
             MINIATURE                 1/2 bushel cartons  09/24/2016
             PIE TYPE                      bushel cartons  09/02/2017
NEW YORK     BIG MACK TYPE                           each  09/24/2016
             HOWDEN TYPE                     36 inch bins  09/16/2017
             KNUCKLE HEAD                    36 inch bins  10/08/2016
             MINIATURE                     bushel cartons  09/09/2017
             MIXED HEIRLOOM VARIETIES        24 inch bins  10/08/2016
             PIE TYPE                      bushel cartons  09/09/2017
PHILADELPHIA HOWDEN TYPE                     36 inch bins  09/16/2017
             KNUCKLE HEAD                    24 inch bins  10/08/2016
             MINIATURE                 1/2 bushel cartons  08/26/2017
             PIE TYPE                        24 inch bins  08/26/2017

                                                  Low Price      High Price  \
                                              max       min  max        min
City Name    Variety
BOSTON       BIG MACK TYPE             11/05/2016       175  260      175.0
             BLUE TYPE                 11/05/2016       260  260      285.0
             CINDERELLA                11/05/2016       260  260      285.0
             FAIRYTALE                 11/05/2016        15  260       16.0
             HOWDEN TYPE               11/05/2016       130  200      160.0
             KNUCKLE HEAD              11/05/2016       260  260      285.0
             MINIATURE                 11/05/2016        15   15       18.0
             PIE TYPE                  12/10/2016        15  300       16.0
NEW YORK     BIG MACK TYPE             10/01/2016        75   75       80.0
             HOWDEN TYPE               11/05/2016       100  180      130.0
             KNUCKLE HEAD              10/08/2016       120  120      140.0
             MINIATURE                 11/05/2016        15   32       16.0
             MIXED HEIRLOOM VARIETIES  10/08/2016       200  200      200.0
             PIE TYPE                  11/05/2016        16  260       18.0
PHILADELPHIA HOWDEN TYPE               10/29/2016       100  150      120.0
             KNUCKLE HEAD              10/08/2016       210  210      210.0
             MINIATURE                 11/05/2016        15   18       15.0
             PIE TYPE                  10/29/2016        12  250       12.0

                                             Mostly Low      Mostly High  \
                                         max        min  max         min
City Name    Variety
BOSTON       BIG MACK TYPE             285.0        175  285       175.0
             BLUE TYPE                 285.0        285  285       285.0
             CINDERELLA                285.0        285  285       285.0
             FAIRYTALE                 285.0         15  285        15.0
             HOWDEN TYPE               225.0        135  225       140.0
             KNUCKLE HEAD              285.0        285  285       285.0
             MINIATURE                  18.0         15   15        15.0
             PIE TYPE                  300.0         15  300        15.0
NEW YORK     BIG MACK TYPE              80.0         75   75        80.0
             HOWDEN TYPE               190.0        100  180       130.0
             KNUCKLE HEAD              140.0        120  120       140.0
             MINIATURE                  32.0         15   32        16.0
             MIXED HEIRLOOM VARIETIES  200.0        200  200       200.0
             PIE TYPE                  300.0         16  260        18.0
PHILADELPHIA HOWDEN TYPE               160.0        100  150       120.0
             KNUCKLE HEAD              210.0        210  210       210.0
             MINIATURE                  20.0         15   18        15.0
             PIE TYPE                  250.0         12  250        12.0

                                             Repack             Origin  \
                                         max    min max            min
City Name    Variety
BOSTON       BIG MACK TYPE             285.0      N   N  MASSACHUSETTS
             BLUE TYPE                 285.0      N   N  MASSACHUSETTS
             CINDERELLA                285.0      N   N  MASSACHUSETTS
             FAIRYTALE                 285.0      N   N  MASSACHUSETTS
             HOWDEN TYPE               225.0      N   N         CANADA
             KNUCKLE HEAD              285.0      N   N  MASSACHUSETTS
             MINIATURE                  15.0      N   N  MASSACHUSETTS
             PIE TYPE                  300.0      N   N         CANADA
NEW YORK     BIG MACK TYPE              80.0      N   N     NEW JERSEY
             HOWDEN TYPE               190.0      N   N       MICHIGAN
             KNUCKLE HEAD              140.0      N   N   PENNSYLVANIA
             MINIATURE                  32.0      N   N       NEW YORK
             MIXED HEIRLOOM VARIETIES  200.0      N   N       MICHIGAN
             PIE TYPE                  300.0      N   N       MICHIGAN
PHILADELPHIA HOWDEN TYPE               160.0      N   N       DELAWARE
             KNUCKLE HEAD              210.0      N   N     NEW JERSEY
             MINIATURE                  20.0      N   N       MICHIGAN
             PIE TYPE                  250.0      N   N       DELAWARE


                                                 max
City Name    Variety
BOSTON       BIG MACK TYPE              PENNSYLVANIA
             BLUE TYPE                 MASSACHUSETTS
             CINDERELLA                MASSACHUSETTS
             FAIRYTALE                 MASSACHUSETTS
             HOWDEN TYPE                PENNSYLVANIA
             KNUCKLE HEAD              MASSACHUSETTS
             MINIATURE                 MASSACHUSETTS
             PIE TYPE                        VERMONT
NEW YORK     BIG MACK TYPE                NEW JERSEY
             HOWDEN TYPE                PENNSYLVANIA
             KNUCKLE HEAD               PENNSYLVANIA
             MINIATURE                          OHIO
             MIXED HEIRLOOM VARIETIES       MICHIGAN
             PIE TYPE                   PENNSYLVANIA
PHILADELPHIA HOWDEN TYPE                PENNSYLVANIA
             KNUCKLE HEAD                 NEW JERSEY
             MINIATURE                          OHIO
             PIE TYPE                   PENNSYLVANIA

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [59]:
# Try the bonus mission if you have time!